/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    companies: Company;
    'company-events': CompanyEvent;
    categories: Category;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    'company-events': CompanyEventsSelect<false> | CompanyEventsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Author bio for E-E-A-T signal (appears at bottom of articles)
   */
  bio: string;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  /**
   * 公司全名（如：Taiwan Semiconductor Manufacturing Company）
   */
  name: string;
  /**
   * 如：2330.TW, AAPL, MSFT
   */
  ticker: string;
  /**
   * Primary stock exchange listing
   */
  exchange?: ('NYSE' | 'NASDAQ' | 'TPE' | 'HKEX' | 'other') | null;
  status: 'watching' | 'analyzing' | 'holding' | 'excluded';
  /**
   * 如：半導體、軟體、金融
   */
  industry?: string | null;
  /**
   * 如：Taiwan, USA, China
   */
  country?: string | null;
  /**
   * IR 網站或公司官網
   */
  website?: string | null;
  /**
   * routine=季報/年報時收集, enhanced=每週, intensive=每日
   */
  monitoring_level?: ('routine' | 'enhanced' | 'intensive') | null;
  /**
   * 用逗號分隔，如：paypal, $pypl, dan schulman
   */
  monitoring_keywords?: string | null;
  /**
   * 其他重要資訊或觀察
   */
  notes?: string | null;
  /**
   * 管理層 Commitment 達成率（0-100%）
   */
  integrity_score?: number | null;
  integrity_status?: ('pass' | 'warning' | 'fail') | null;
  /**
   * 記錄管理層承諾與實際達成情況
   */
  integrity_notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 以億或百萬為單位，須註明幣別
   */
  latest_oe?: number | null;
  oe_currency?: ('TWD' | 'USD' | 'CNY') | null;
  /**
   * 業主盈餘的 7 年平均複合成長率
   */
  historical_cagr_7y?: number | null;
  /**
   * 流通在外股數
   */
  total_shares?: number | null;
  /**
   * Allen Framework parameter: fraction of capex that is maintenance (e.g. 0.20 for TSMC)
   */
  maintenance_capex_ratio?: number | null;
  /**
   * 財報來源、計算方法、特殊調整等
   */
  historical_notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 保守估計的信心係數（如 0.8, 1.0）
   */
  confidence_low?: number | null;
  /**
   * 樂觀估計的信心係數（如 1.3, 1.5）
   */
  confidence_high?: number | null;
  /**
   * 計算結果：Latest OE × Confidence Low
   */
  iv_total_low?: number | null;
  /**
   * 計算結果：Latest OE × Confidence High
   */
  iv_total_high?: number | null;
  /**
   * 計算結果：IV Total Low / Total Shares
   */
  iv_per_share_low?: number | null;
  /**
   * 計算結果：IV Total High / Total Shares
   */
  iv_per_share_high?: number | null;
  /**
   * 重大資本支出、新產品、市場擴張等
   */
  forward_factors?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 當前股價
   */
  current_price?: number | null;
  price_updated_at?: string | null;
  /**
   * (Current Price / IV Mid) - 1
   */
  deviation_percentage?: number | null;
  investment_decision?: ('buy' | 'hold' | 'watch' | 'sell') | null;
  /**
   * 模擬股價大跌 50% 時的質押保證金缺口
   */
  stress_test_50?: number | null;
  /**
   * 決策依據、風險評估、操作計畫
   */
  navigation_notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-events".
 */
export interface CompanyEvent {
  id: number;
  company: number | Company;
  /**
   * 事件發生或發現的時間
   */
  event_date: string;
  source: 'x-twitter' | 'news' | 'sec-filing' | 'earnings-call' | 'financial-report' | 'company-announcement' | 'other';
  importance?: ('low' | 'medium' | 'high' | 'critical') | null;
  /**
   * 簡短描述事件（一行）
   */
  title: string;
  /**
   * 事件重點摘要（幾句話）
   */
  summary?: string | null;
  /**
   * 完整原文或截取內容
   */
  raw_content?: string | null;
  source_url?: string | null;
  /**
   * 用逗號分隔，如：revenue, layoff, new-product
   */
  keywords?: string | null;
  /**
   * 此事件對 IVC 信心係數的潛在影響方向
   */
  ivco_impact?: ('positive' | 'neutral' | 'negative' | 'pending') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-friendly name (e.g. value-investing)
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL path (e.g. tsmc-intrinsic-value-case-study)
   */
  slug: string;
  author: number | Author;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Preview text for cards and RSS (optional, falls back to seo.description)
   */
  excerpt?: string | null;
  category: number | Category;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Link to company if this is a case study or analysis
   */
  relatedCompany?: (number | null) | Company;
  coverImage?: (number | null) | Media;
  status: 'draft' | 'ai_reviewing' | 'ready' | 'published';
  publishedAt?: string | null;
  seo: {
    /**
     * SERP title (max 60 characters)
     */
    title: string;
    /**
     * SERP description (max 160 characters)
     */
    description: string;
    /**
     * Social sharing preview (1200x630). Falls back to /api/og dynamic generation if empty.
     */
    ogImage?: (number | null) | Media;
    /**
     * Only if cross-posted elsewhere
     */
    canonicalUrl?: string | null;
  };
  /**
   * Required for FAQPage structured data. Minimum 3 Q&A pairs.
   */
  faq: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  schema: {
    /**
     * Turn on for step-by-step articles (e.g. TSMC Case Study)
     */
    enableHowTo?: boolean | null;
    /**
     * E-E-A-T signal — author bio specific to this article's topic
     */
    authorBio: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'company-events';
        value: number | CompanyEvent;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  ticker?: T;
  exchange?: T;
  status?: T;
  industry?: T;
  country?: T;
  website?: T;
  monitoring_level?: T;
  monitoring_keywords?: T;
  notes?: T;
  integrity_score?: T;
  integrity_status?: T;
  integrity_notes?: T;
  latest_oe?: T;
  oe_currency?: T;
  historical_cagr_7y?: T;
  total_shares?: T;
  maintenance_capex_ratio?: T;
  historical_notes?: T;
  confidence_low?: T;
  confidence_high?: T;
  iv_total_low?: T;
  iv_total_high?: T;
  iv_per_share_low?: T;
  iv_per_share_high?: T;
  forward_factors?: T;
  current_price?: T;
  price_updated_at?: T;
  deviation_percentage?: T;
  investment_decision?: T;
  stress_test_50?: T;
  navigation_notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-events_select".
 */
export interface CompanyEventsSelect<T extends boolean = true> {
  company?: T;
  event_date?: T;
  source?: T;
  importance?: T;
  title?: T;
  summary?: T;
  raw_content?: T;
  source_url?: T;
  keywords?: T;
  ivco_impact?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  content?: T;
  excerpt?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedCompany?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        canonicalUrl?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  schema?:
    | T
    | {
        enableHowTo?: T;
        authorBio?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}